/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

/* Copyright 2026 Oxide Computer Company */

/*
 * AMD IOMMU Driver
 * ================
 * This is the driver for the AMD IOMMU for the Oxide architecture.
 * The IOMMU is documented in AMD publication 48882; at the time of writing,
 * version 3.11 is the current version.
 *
 * Overview
 * --------
 * The IOMMU is capable of doing several things:
 *
 *  - It can virtualize the host address space as seen by a device
 *  - It can remap interrupts generated by a device, and direct them to a
 *    specific CPU or logical group of CPUs, at a specific vector
 *  - It can handle direct delivery of interrupts into a virtual machine, by
 *    manipulating the guest's virtual APIC state
 *  - It can present a "second level" virtual APIC so that it can be
 *    virtualized itself.
 *
 * From this rich suite of functionality, the Oxide architecture presently only
 * supports interrupt remapping.  We use this so that we can support device
 * interrupt delivery to high-numbered CPUs on large machines: in particular,
 * when considering PCIe devices, neither MSI nor MSI-X directly support the
 * full width of the APIC ID space.  However, with appropriate configuration
 * the IOMMU does: thus, to direct interrupts to those devices, we remap them
 * through the IOMMU.
 *
 * How The IOMMU Remaps Interrupts
 * -------------------------------
 * Each SoC has some number of integrated IO hubs, each of which has an
 * integrated IOMMU "L1" that monitors device traffic, if the IOMMU is enabled,
 * forwards memory and interrupt accesses on to an IOMMU "L2".  Each IOMMU is
 * configured to point to a _Device Table_, indexed by a _Device ID_, that says
 * what to do with accesses for a particular device.
 *
 * When interrupt messages arrive at an IOMMU, the device table is indexed by
 * the Device ID of the device that generated the interrupt message; for PCIe
 * devices, this is a 16-bit PCI BDF; for external devices connected to an
 * IOAPIC and for internal devices, the DeviceID is synthesized to look like a
 * BDF; the synthesized ID is derived from the internal topology of the SoC and
 * described in detail in a PPR.
 *
 * The indexed _Device Table Entry_ (DTE) contains a set of control bits
 * defining if and how interrupt remapping should be handled, and a pointer to
 * the base of a per-device _Interrupt Remapping Table_ (IRT).  If remapping is
 * enabled, the interrupt is looked up in the IRT; the index into the IRT is
 * derived from data bits 10:0 of the MSI(-X) interrupt message.  The address in
 * the MSI interrupt message is ignored.
 *
 * The interrupt table entry (IRTE), in turn, contains information about the
 * remapped interrupt and where it will be delivered, including:
 *
 *  - What kind of interrupt should be generated (Fixed, NMI, etc)
 *  - The LAPIC ID of the destination logical processor
 *  - The remapped interrupt's vector number
 *  - Trigger and Destination Mode, etc
 *
 * Pictorally, this diagram represents the relationships between components:
 *
 *    +--------+   +--------+         +--------+
 *    |  IOMS  |   |  IOMS  |         |  IOMS  |
 *    |  +-----+   |  +-----+   ...   |  +-----+
 *    |  |IOMMU|   |  |IOMMU|         |  |IOMMU|
 *    +--+-----+   +--+-----+         +--+-----+
 *         \           |                 /
 *          \          |                /
 *           \-----\   |       /-------/
 *                  \  |      /
 *                 +-----------+    +-------------+
 *                 |           |----|IRT (per dev)|
 *                 |           |    +-------------+
 *                 |           |
 *                 |  Device   |    +-------------+
 *                 |   Table   |----|IRT (per dev)|
 *                 |           |    +-------------+
 *                 |(Shared by |
 *                 |all IOMMUs |           .
 *                 |  on this  |           .
 *                 | segment)  |           .
 *                 |           |
 *                 |           |    +-------------+
 *                 |           |----|IRT (per dev)|
 *                 +-----------+    +-------------+
 *
 * Note that the device table is shared by all IOMMUs on a PCI segment, as the
 * BDF space covers all devices, including IOAPICs, is only unique per segment.
 * As the IOMMUs are already sharing the device space, they can also share the
 * device table.
 *
 * Note that AMD doesn't use our segment-oriented terminology, but we do, as
 * that provides a conceptually intuitive framing for the relationships between
 * components.
 *
 * ### Addressing Logical Processors with APIC IDs >254
 *
 * Using the interrupt remapping capabilities of the IOMMU can permit directing
 * device interrupts to logical processors with LAPIC ID numbers >254.  The
 * challenge is that the data formats programmed into an IOAPIC and into the
 * MSI and MSI-X data and address pairs for PCIe devices only permit an 8-bit
 * APIC ID, but entries in the device table allow us to specify use of an
 * extended form of interrupt remapping table entries, which supports giving
 * the full 32-bit destination x2APIC ID for the remapped interrupt.
 *
 * Note that it is not necessary to have more than 254 logical processors in a
 * system to have a LAPIC ID >254: consider a 2P system, in which the system
 * may accommodate processors with up to some number of logical processors
 * greater than 256, but with substantially fewer (say, 64 cores and 128 LPs).
 * Then the system may number cores for the processor in the second socket
 * starting from the maximum number of LPs per socket.
 *
 * That is, if each socket could accommodate a 128C/256T CPU, but a 64C/128T
 * CPU was installed in each socket, then LPs on the package in the first
 * socket might be numbered [0,..,128), LPs in the second socket may be numbered
 * [256,..,384), and the machine has a total of 256 LPs.
 *
 * ### Addressing Interrupts Generated by the IOMMU to High ID CPUs
 *
 * The ability to use the IOMMU in multi-segment systems (or single-segment
 * systems with high core-count CPUs) raises a question: the IOMMU is
 * architecturally prohibited from remapping interrupts that it generates
 * itself: how, then, can those be directed to CPUs with APIC IDs that do not
 * fit into 8 bits?
 *
 * To address this, the IOMMU can be specially configured via registers
 * similar to MSI data and address pairs, but which support a 32-bit x2APIC
 * ID for the destination CPU; this mechanism is unique to the IOMMU, and
 * exists outside of the other standard mechanisms for specifying an
 * interrupt's destination.
 *
 * ### Caveat: the 8259A
 *
 * One caveat to be aware of is that interrupts delivered through the legacy
 * 8259A ("Programmable Interrupt Controller" [PIC]) are not remapped through
 * the IOMMU.
 *
 * Interrupt Remapping in the Oxide Architecture
 * ---------------------------------------------
 * The Oxide architecture already unconditionally uses the x2APIC, and each
 * logical processor has its own LAPIC timer, so CPUs with high LAPIC IDs are
 * usable without additional changes: they can send and receive IPIs,
 * participate in cross-calls, and can generate and receive timer interrupts
 * for scheduling and preemption.  We use the interrupt remapping via the
 * IOMMU so that peripheral interrupts can be directed to those CPUs, as well.
 *
 * Using the IOMMU also provides mechanisms allowing us to suppress sending of
 * SMI, INIT, SIPI, and NMI interrupts from devices that should never send
 * those.  Of that set, only NMIs are of interest to us in any way, and those
 * should only be sent as IPIs or generated from the FCH.
 *
 * Oxide machines currently have exactly one PCIe segment, and a single device
 * table is shared by all IOMMUs in the system.  Except for interrupts
 * originating from an IOMMU itself, all device interrupts are routed through
 * an IOMMU.  Each DTE points to a unique IRT, specific to the interrupt source
 * corresponding to that DeviceID; within a given IRT, IRTEs are allocated
 * sequentially, starting from entry 0 up to a configured limit, currently 256.
 *
 * For simplicity, we allocate a single device table spanning the entire 16-bit
 * BDF space.  Each DTE is 256 (2^8) bits long, and there are 65536 (2^16)
 * entries, so the total space required, expressed in 8-bit (2^3) bytes, is
 * thus 2^(8-3+16) = 2^21 bytes, or 2MiB.  We do not use Device Table
 * Segmentation at this time.
 *
 * To avoid excessive fragmentation of physical memory, we allocate a single
 * 4KiB page frame for each IRT.  Using the extended format, IRTEs are 128
 * (2^7) bits, or 2^4=16 bytes, long.  Thus, despite the hardware supporting a
 * full 11-bit IRTE index, we artificially limit the number of interrupts per
 * IRT to 256.
 */

#include <sys/conf.h>
#include <sys/cred.h>
#include <sys/ddi.h>
#include <sys/devops.h>
#include <sys/errno.h>
#include <sys/file.h>
#include <sys/modctl.h>
#include <sys/open.h>
#include <sys/policy.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/x86_archext.h>

#include <sys/amd_iommu.h>

#define	AMD_IOMMU_NODETYPE	"ddi_iommu"
#define	AMD_IOMMU_MINOR_NAME	"amd-iommu"

static int amd_iommu_getinfo(dev_info_t *dip, ddi_info_cmd_t cmd, void *arg,
    void **result);
static int amd_iommu_attach(dev_info_t *dip, ddi_attach_cmd_t cmd);
static int amd_iommu_detach(dev_info_t *dip, ddi_detach_cmd_t cmd);
static int amd_iommu_open(dev_t *devp, int flag, int otyp, cred_t *credp);
static int amd_iommu_close(dev_t dev, int flag, int otyp, cred_t *credp);
static int amd_iommu_ioctl(dev_t dev, int cmd, intptr_t arg, int mode,
    cred_t *credp, int *rvalp);
static int amd_iommu_quiesce(dev_info_t *dip);

static struct cb_ops amd_iommu_cb_ops = {
	.cb_open = amd_iommu_open,
	.cb_close = amd_iommu_close,
	.cb_strategy = nodev,
	.cb_print = nodev,
	.cb_dump = nodev,
	.cb_read = nodev,
	.cb_write = nodev,
	.cb_ioctl = amd_iommu_ioctl,
	.cb_devmap = nodev,
	.cb_mmap = nodev,
	.cb_segmap = nodev,
	.cb_chpoll = nochpoll,
	.cb_prop_op = ddi_prop_op,
	.cb_str = NULL,
	.cb_flag = D_NEW | D_MP,
	.cb_rev = CB_REV,
	.cb_aread = nodev,
	.cb_awrite = nodev,
};

static struct dev_ops amd_iommu_dev_ops = {
	.devo_rev = DEVO_REV,
	.devo_refcnt = 0,
	.devo_getinfo = amd_iommu_getinfo,
	.devo_identify = nulldev,
	.devo_probe = nulldev,
	.devo_attach = amd_iommu_attach,
	.devo_detach = amd_iommu_detach,
	.devo_reset = nodev,
	.devo_cb_ops = &amd_iommu_cb_ops,
	.devo_bus_ops = NULL,
	.devo_power = nulldev,
	.devo_quiesce = amd_iommu_quiesce,
};

static struct modldrv modldrv = {
	&mod_driverops,
	"AMD IOMMU",
	&amd_iommu_dev_ops
};

static struct modlinkage modlinkage = {
	MODREV_1,
	(void *)&modldrv,
	NULL
};

static void *amd_iommu_soft_state;

static int
amd_iommu_soft_state_init(void)
{
	const size_t NIOMMU = 1;
	return (ddi_soft_state_init(&amd_iommu_soft_state,
	    sizeof (amd_iommu_state_t), NIOMMU));
}

static void
amd_iommu_soft_state_fini(void)
{
	ddi_soft_state_fini(&amd_iommu_soft_state);
	amd_iommu_soft_state = NULL;
}

int
_init(void)
{
	int err;

	if (get_hwenv() != HW_NATIVE)
		return (ENOTSUP);

	err = amd_iommu_soft_state_init();
	if (err != 0) {
		cmn_err(CE_WARN,
		    "amd_iommu: _init: failed to initialize soft state.");
		return (err);
	}

	err = mod_install(&modlinkage);
	if (err != 0) {
		cmn_err(CE_WARN, "amd_iommu: _init: mod_install failed.");
		amd_iommu_soft_state_fini();
		return (err);
	}

	return (0);
}

int
_info(struct modinfo *mip)
{
	return (mod_info(&modlinkage, mip));
}

int
_fini(void)
{
	int err;

	err = mod_remove(&modlinkage);
	if (err != 0)
		return (err);

	amd_iommu_soft_state_fini();

	return (0);
}

static int
amd_iommu_getinfo(dev_info_t *dip __unused, ddi_info_cmd_t cmd, void *arg,
    void **result)
{
	ASSERT3P(result, !=, NULL);

	dev_t dev = (dev_t)arg;
	minor_t minor = getminor(dev);
	amd_iommu_state_t *iommu;
	switch (cmd) {
	case DDI_INFO_DEVT2DEVINFO:
		iommu = ddi_get_soft_state(amd_iommu_soft_state, minor);
		if (iommu == NULL || iommu->aioms_devi == NULL) {
			*result = NULL;
			return (DDI_FAILURE);
		}
		*result = iommu->aioms_devi;
		break;
	case DDI_INFO_DEVT2INSTANCE:
		*result = (void *)(uintptr_t)minor;
		break;
	}

	return (DDI_SUCCESS);
}

static int
amd_iommu_attach(dev_info_t *devi, ddi_attach_cmd_t cmd)
{
	int instance = ddi_get_instance(devi);
	const char *driver = ddi_driver_name(devi);
	amd_iommu_state_t *iommu;
	int err;

	ASSERT3S(instance, >=, 0);
	ASSERT3P(driver, !=, NULL);

	switch (cmd) {
	case DDI_ATTACH:
		break;
	case DDI_RESUME:
		return (DDI_SUCCESS);
	default:
		return (DDI_FAILURE);
	}

	err = ddi_soft_state_zalloc(amd_iommu_soft_state, instance);
	if (err != DDI_SUCCESS) {
		cmn_err(CE_WARN, "Unable to allocate soft state for %s%d",
		    driver, instance);
		return (DDI_FAILURE);
	}

	iommu = ddi_get_soft_state(amd_iommu_soft_state, instance);
	if (iommu == NULL) {
		cmn_err(CE_WARN, "Unable to get soft state for "
		    "%s%d", driver, instance);
		ddi_soft_state_free(amd_iommu_soft_state, instance);
		return (DDI_FAILURE);
	}

	err = ddi_create_minor_node(devi, AMD_IOMMU_MINOR_NAME, S_IFCHR,
	    instance, AMD_IOMMU_NODETYPE, 0);
	if (err != DDI_SUCCESS) {
		cmn_err(CE_WARN, "Unable to create minor node for %s%d",
		    driver, instance);
		ddi_remove_minor_node(devi, NULL);
		ddi_soft_state_free(amd_iommu_soft_state, instance);
		return (DDI_FAILURE);
	}

	iommu->aioms_devi = devi;
	iommu->aioms_instance = instance;
	iommu->aioms_iommu_start = NULL;
	iommu->aioms_iommu_end = NULL;

	ddi_set_driver_private(devi, iommu);
	ddi_report_dev(devi);

	return (DDI_SUCCESS);
}

static int
amd_iommu_detach(dev_info_t *dip, ddi_detach_cmd_t cmd)
{
	/*
	 * The IOMMU cannot be detached; suspension is the only operation
	 * that results in success.
	 */
	if (cmd == DDI_SUSPEND)
		return (DDI_SUCCESS);
	return (DDI_FAILURE);
}

static int
amd_iommu_open(dev_t *devp, int flag, int otyp, cred_t *credp)
{
	int instance;
	amd_iommu_state_t *iommu;

	instance = getminor(*devp);
	if (instance < 0) {
		cmn_err(CE_WARN, "amd_iommu_open: invalid instance %d",
		    instance);
		return (ENXIO);
	}
	if ((flag & (FEXCL | FNDELAY | FNONBLOCK | FWRITE)) != 0) {
		cmn_err(CE_WARN, "amd_iommu_open: invalid flags %d", flag);
		return (EINVAL);
	}
	if (otyp != OTYP_CHR) {
		cmn_err(CE_WARN, "amd_iommu_open: invalid otyp %d", otyp);
		return (EINVAL);
	}
	if (crgetzoneid(credp) != GLOBAL_ZONEID ||
	    secpolicy_hwmanip(credp) != 0) {
		return (EPERM);
	}

	iommu = ddi_get_soft_state(amd_iommu_soft_state, instance);
	if (iommu == NULL) {
		cmn_err(CE_WARN,
		    "amd_iommu_open: cannot get soft state: instance %d",
		    instance);
		return (ENXIO);
	}

	ASSERT3S(iommu->aioms_instance, ==, instance);

	return (0);
}

static int
amd_iommu_close(dev_t dev, int flag __unused, int otyp __unused,
    cred_t *credp __unused)
{
	int instance;
	amd_iommu_state_t *iommu;

	instance = getminor(dev);
	if (instance < 0) {
		cmn_err(CE_WARN, "amd_iommu_close: invalid instance %d",
		    instance);
		return (ENXIO);
	}

	iommu = ddi_get_soft_state(amd_iommu_soft_state, instance);
	if (iommu == NULL) {
		cmn_err(CE_WARN,
		    "amd_iommu_close: cannot get soft state: instance %d",
		    instance);
		return (ENXIO);
	}
	ASSERT3S(iommu->aioms_instance, ==, instance);

	return (0);

}

static int
amd_iommu_ioctl(dev_t dev, int cmd __unused, intptr_t arg __unused, int mode,
    cred_t *credp __unused, int *rvalp __unused)
{
	int instance = getminor(dev);
	amd_iommu_state_t *iommu;

	ASSERT3P(rvalp, !=, NULL);

	if (instance < 0) {
		cmn_err(CE_WARN, "amd_iommu_ioctl: invalid instance %d",
		    instance);
		return (ENXIO);
	}


	if ((mode & (FEXCL | FNDELAY | FNONBLOCK | FWRITE)) != 0) {
		cmn_err(CE_WARN, "amd_iommu_ioctl: invalid mode %d", mode);
		return (EINVAL);
	}

	if ((mode & FKIOCTL) != 0) {
		cmn_err(CE_WARN, "amd_iommu_ioctl: FKIOCTL unsupported mode %d",
		    mode);
		return (EINVAL);
	}

	iommu = ddi_get_soft_state(amd_iommu_soft_state, instance);
	if (iommu == NULL) {
		cmn_err(CE_WARN,
		    "amd_iommu_ioctl: cannot get soft state: instance %d",
		    instance);
		return (ENXIO);
	}

	ASSERT3S(iommu->aioms_instance, ==, instance);

	return (ENOTTY);
}

static int
amd_iommu_quiesce(dev_info_t *devi)
{
	int instance;
	amd_iommu_state_t *iommu;

	instance = ddi_get_instance(devi);
	if (instance < 0) {
		cmn_err(CE_WARN, "amd_iommu_ioctl: invalid instance %d",
		    instance);
		return (ENXIO);
	}

	iommu = ddi_get_soft_state(amd_iommu_soft_state, instance);
	if (iommu == NULL) {
		cmn_err(CE_WARN,
		    "amd_iommu_quiesce: cannot get soft state: instance %d",
		    instance);
		return (DDI_FAILURE);
	}

	return (DDI_SUCCESS);
}
