#!/bin/ksh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Oxide Computer Company
#

. /lib/svc/share/smf_include.sh

# This service creates a DPIO (Dedicated Purpose I/O) for the Chelsio T6
# pin that controls whether it comes up in manufacturing or mission mode
# and then invokes the process that verifies/programs the device as necessary
# before putting it into mission mode.
#
# It contains hard-coded knowledge of the required parameters based on the
# platform, which will need extending to support future systems.

# GPIO location based on platform
typeset -rA GPIOMAP=(
	[Oxide,Gimlet]=(
		[controller]=zen_gpio0
		[gpio]=EGPIO9_3
		[attachment]=pcie16
		[pci_subsystem_device_id]=0xfff9
	)
)

smf_is_globalzone || exit $SMF_EXIT_OK

# Running this script with "mfgmode" as the sole argument is a development aid
# that allows for quick switching back to manufacturing mode and does not have
# to be run from smf(7).
if [[ "$1" != "mfgmode" && -z "$SMF_FMRI" ]]; then
        echo "this script can only be invoked by smf(7)"
        exit $SMF_EXIT_ERR_NOSMF
fi

function scream {
	logger -p kern.notice -t t6init "$@"
	cat <<-EOM | tee -a /dev/console

		$(printf "%0.s#" {1..78})
		#### NOTE: T6 PROBLEM
		#### $@
		$(printf "%0.s#" {1..78})
	EOM
}

function fatal {
	scream "$@"
	echo "$@" >&2
	exit $SMF_EXIT_ERR_FATAL
}

typeset -r GPIOADM=/usr/sbin/gpioadm
typeset -r PCIEADM=/usr/lib/pci/pcieadm

typeset -r PLATFORM=$(prtconf /devices)
typeset -r ARCH=$(uname -m)

typeset -r DPIO_NAME=t6mission

typeset -r T6INIT=/usr/platform/$ARCH/bin/t6init
typeset -r SROM_FILE="/platform/$PLATFORM/firmware/t6srom.bin"
typeset -r FW_FILE="/kernel/firmware/cxgbe/t6fw.bin"

if [[ -z "${GPIOMAP[$PLATFORM]}" ]]; then
	echo "$SMF_FMRI is not supported for $PLATFORM"
	/usr/sbin/svcadm disable $SMF_FMRI
	# This sleep is here to allow the effect of the 'svcadm disable'
	# to propagate through to the repository in order to work around a race
	# condition where the service may start up again. Once illumos
	# 15320 is resolved, it should be removed in favour of this script
	# exiting with the new $SMF_EXIT_TEMP_DISABLE
	sleep 5 &
	exit $SMF_EXIT_OK
fi

[[ -f "$SROM_FILE" ]] || fatal "SROM file $SROM_FILE not found"
[[ -f "$FW_FILE" ]] || fatal "FW file $FW_FILE not found"

typeset -r CTRL="${GPIOMAP[$PLATFORM][controller]}"
typeset -r GPIO="${GPIOMAP[$PLATFORM][gpio]}"
typeset -r ATTACH_POINT="${GPIOMAP[$PLATFORM][attachment]}"
typeset -r PCISSDID="${GPIOMAP[$PLATFORM][pci_subsystem_device_id]}"

if [[ -z "$CTRL" || -z "$GPIO" || -z "$ATTACH_POINT" || -z "$PCISSDID" ]]; then
	echo "Could not determine controller/gpio for $PLATFORM"
	exit $SMF_EXIT_ERR_CONFIG
fi

function create_dpio {
	typeset existing=$($GPIOADM dpio list -Hpo controller,gpionum \
	    $DPIO_NAME 2>/dev/null)

	if (($? == 0)) && [[ -n "$existing" ]]; then
		return
	fi

	echo "Configuring GPIO attributes"

	typeset cur=$($GPIOADM gpio attr get -po value "$CTRL/$GPIO" zen:output)
	if [[ "$cur" == "disabled" ]]; then
		$GPIOADM gpio attr set "$CTRL/$GPIO" "zen:output=low" ||
		    fatal "Failed to configure GPIO output"
	fi

	$GPIOADM gpio attr set "$CTRL/$GPIO" "zen:pull=disabled" ||
	    fatal "Failed to disable GPIO pulldown/up"

	echo "Creating DPIO $DPIO_NAME over $CTRL/$GPIO"
	$GPIOADM dpio define -rw "$CTRL/$GPIO" "$DPIO_NAME" || \
	    fatal "Failed to define DPIO"

	# Work around stlouis#294
	echo "Waiting for DPIO device to appear"
	while [[ ! -r /dev/dpio/$DPIO_NAME ]]; do
		sleep 1
		echo "  ... waiting"
	done
}

function check_link {
	typeset dev=$1; shift
	typeset espeed=$1; shift
	typeset ewidth=$1; shift

	instlist=$($PCIEADM show-devs -Ho instnum $dev)
	if (($? != 0)); then
		scream "No $dev devices"
		return
	fi
	for inst in $instlist; do
		d="$dev$inst"
		speed=$($PCIEADM show-cfgspace -d $d \
		    -Hpo value pcie.linksts.speed)
		width=$($PCIEADM show-cfgspace -d $d \
		    -Hpo value pcie.linksts.width)
		((speed == espeed)) || \
			scream "wrong $d speed $speed (want $espeed)"
		((width == ewidth)) || \
			scream "wrong $d width $width (want $ewidth)"
	done
}

case "$1" in
start)
	create_dpio

	check_link t6mfg 0x2 0x8

	echo "Attempting to transition to mission mode"
	$T6INIT \
	    -v \
	    -D $DPIO_NAME \
	    -A $ATTACH_POINT \
	    -s $SROM_FILE \
	    -f $FW_FILE \
	    -P $PCISSDID || fatal "Failed to transition to mission mode"

	check_link t4nex 0x3 0x10
	;;
stop)
	# No action taken on stop
	;;
mfgmode)
	create_dpio
	echo "Attempting to transition to manufacturing mode"
	$T6INIT \
	    -v \
	    -M \
	    -D $DPIO_NAME \
	    -A $ATTACH_POINT || fatal "Failed to transition to mfg mode"
	;;
*)
	fatal "ERROR: $0: unsupported command '$1'"
	;;
esac

exit $SMF_EXIT_OK
