# Copyright 2022 Oxide Computer Company

MODULE = tofino.so
MDBTGT = kvm

MODSRCS = tofino.c

include ../../../../Makefile.cmd
include ../../../../Makefile.cmd.64
include ../../Makefile.amd64
include ../../../Makefile.module
