/*
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source.  A copy of the CDDL is also available via the Internet at
 * http://www.illumos.org/license/CDDL.
 */

/*
 * Copyright 2022 Oxide Computer Company
 */

/*
 * This contains SP3 specific data related to the processor's pins, GPIOs, and
 * I/O Mux.
 */

#include <sys/sysmacros.h>
#include "amdzen_data.h"

#define	SP3_MUX_ENTRY(m0, m1, m2, m3) \
	.zg_iomux = { SP3_SIGNAL_ ## m0, SP3_SIGNAL_ ## m1, \
	SP3_SIGNAL_ ## m2, SP3_SIGNAL_ ## m3 }

/*
 * This currently covers Rome and Milan based SP3 CPUs.
 */
const zen_gpio_pindata_t zen_gpio_sp3_data[] = { {
	.zg_name = "AGPIO0",
	.zg_signal = "BP_PWR_BTN_L",
	.zg_pin = "A29",
	.zg_id = 0,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PWR_BTN_L, AGPIO0, INVALID, INVALID),
}, {
	.zg_name = "AGPIO1",
	.zg_signal = "BP_SYS_RESET_L",
	.zg_id = 1,
	.zg_pin = "A35",
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(SYS_RESET_L, AGPIO1, INVALID, INVALID),
}, {
	.zg_name = "AGPIO2",
	.zg_signal = "BP_WAKE_L",
	.zg_pin = "B36",
	.zg_id = 2,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(WAKE_L, AGPIO2, INVALID, INVALID),
}, {
	.zg_name = "AGPIO3",
	.zg_signal = "BP_AGPIO3",
	.zg_pin = "CY24",
	.zg_id = 3,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO3, INVALID, INVALID, INVALID),
}, {
	.zg_name = "AGPIO4",
	.zg_signal = "BP_AGPIO4",
	.zg_pin = "E17",
	.zg_id = 4,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO4, INVALID, INVALID, INVALID),
}, {
	.zg_name = "AGPIO5",
	.zg_signal = "BP_AGPIO5",
	.zg_pin = "DB24",
	.zg_id = 5,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO5, DEVSLP0, INVALID, INVALID),
}, {
	.zg_name = "AGPIO6",
	.zg_signal = "BP_AGPIO6",
	.zg_pin = "DA24",
	.zg_id = 6,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO6, DEVSLP1, INVALID, INVALID),
}, {
	.zg_name = "AGPIO9_0",
	.zg_signal = "BP_AGPIO9_0",
	.zg_pin = "DB29",
	.zg_id = 9,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO9_0, SGPIO0_DATAOUT, INVALID, INVALID),
}, {
	.zg_name = "AGPIO10_0",
	.zg_signal = "BP_S0A3_GPIO_0",
	.zg_pin = "DA28",
	.zg_id = 10,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO10_0, INVALID, SGPIO0_CLK, INVALID),
}, {
	.zg_name = "AGPIO12",
	.zg_signal = "BP_PWRGD_OUT",
	.zg_pin = "B30",
	.zg_id = 12,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PWRGD_OUT, AGPIO12, INVALID, INVALID),
}, {
	.zg_name = "AGPIO16_0",
	.zg_signal = "BP_USB_OC0_L",
	.zg_pin = "CY15",
	.zg_id = 16,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(USB_OC0_L, AGPIO16_0, INVALID, INVALID),
}, {
	.zg_name = "AGPIO17_0",
	.zg_signal = "BP_USB_OC1_L",
	.zg_pin = "CY14",
	.zg_id = 17,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(USB_OC1_L, AGPIO17_0, INVALID, INVALID),
}, {
	.zg_name = "AGPIO19",
	.zg_signal = "BP_SCL1",
	.zg_pin = "CW15",
	.zg_id = 19,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S5 | ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(SCL1, I2C3_SCL, AGPIO19, INVALID),
}, {
	.zg_name = "AGPIO20",
	.zg_signal = "BP_SDA1",
	.zg_pin = "CV15",
	.zg_id = 20,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S5 | ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(SDA1, I2C3_SDA, AGPIO20, INVALID),
}, {
	.zg_name = "AGPIO21",
	.zg_signal = "BP_LPC_PD_L",
	.zg_pin = "CV27",
	.zg_id = 21,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(LPC_PD_L, EMMC_CMD, AGPIO21, INVALID),
}, {
	.zg_name = "AGPIO22",
	.zg_signal = "BP_LPC_PME_L",
	.zg_pin = "CV26",
	.zg_id = 22,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(LPC_PME_L, EMMC_PWR_CTRL, AGPIO22, INVALID),
}, {
	.zg_name = "AGPIO23_0",
	.zg_signal = "BP_AGPIO23_0",
	.zg_pin = "CY27",
	.zg_id = 23,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(AGPIO23_0, SGPIO0_LOAD, INVALID, INVALID),
}, {
	.zg_name = "EGPIO26",
	.zg_signal = "BP_PCIE_RST0_L",
	.zg_pin = "DB27",
	.zg_id = 26,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PCIE_RST0_L, EGPIO26, INVALID, INVALID),
}, {
	.zg_name = "EGPIO26_3",
	.zg_signal = "BP_PCIE_RST3_L",
	.zg_pin = "DB21",
	.zg_id = 27,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PCIE_RST3_L, EGPIO26_3, INVALID, INVALID),
}, {
	.zg_name = "EGPIO9_3",
	.zg_signal = "BP_AGPIO9_3",
	.zg_pin = "CY41",
	.zg_id = 29,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO9_3, SGPIO3_DATAOUT, INVALID, INVALID),
}, {
	.zg_name = "EGPIO23_3",
	.zg_signal = "BP_AGPIO23_3",
	.zg_pin = "CY42",
	.zg_id = 30,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO23_3, SGPIO3_LOAD, INVALID, INVALID),
}, {
	.zg_name = "EGPIO10_3",
	.zg_signal = "BP_S0A3_GPIO_3",
	.zg_pin = "DA43",
	.zg_id = 31,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO10_3, SGPIO3_CLK, INVALID, INVALID),
}, {
	.zg_name = "EGPIO40_3",
	.zg_signal = "BP_AGPIO40_3",
	.zg_pin = "DB44",
	.zg_id = 32,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO40_3, SGPIO3_DATAIN, INVALID, INVALID),
}, {
	.zg_name = "AGPIO40_0",
	.zg_signal = "BP_AGPIO40_0",
	.zg_pin = "DA27",
	.zg_id = 40,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO40_0, SGPIO0_DATAIN, INVALID, INVALID),
}, {
	.zg_name = "EGPIO42",
	.zg_signal = "BP_EGPIO42",
	.zg_pin = "CV21",
	.zg_id = 42,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_UNKNOWN,
	SP3_MUX_ENTRY(EGPIO42, INVALID, INVALID, INVALID),
}, {
	/*
	 * This pin's I/O mux entry technically has the third entry (index 2)
	 * listed as the SD card periperhal's clock. While that PCI device
	 * exists, it is not mentioned in the SP3 motherboard guide or FDS, and
	 * thus for now we have opted not to include it here.
	 */
	.zg_name = "EGPIO70",
	.zg_signal = "BP_EGPIO70",
	.zg_pin = "CW25",
	.zg_id = 70,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_UNKNOWN,
	SP3_MUX_ENTRY(EGPIO70, EMMC_CLK, INVALID, INVALID),
}, {
	.zg_name = "EGPIO74",
	.zg_signal = "BP_LPCCLK0",
	.zg_pin = "CV30",
	.zg_id = 74,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LPCCLK0, EMMC_DATA4, EGPIO74, INVALID),
}, {
	.zg_name = "EGPIO75",
	.zg_signal = "BP_LPCCLK1",
	.zg_pin = "CV33",
	.zg_id = 75,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LPCCLK1, EMMC_DATA6, EGPIO75, INVALID),
}, {
	.zg_name = "AGPIO76",
	.zg_signal = "BP_AGPIO76",
	.zg_id = 76,
	.zg_pin = "CY30",
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	.zg_pinovr = ZEN_PIN_OVR_NMI,
	SP3_MUX_ENTRY(AGPIO76, SPI_TPM_CS_L, INVALID, INVALID),
	.zg_override = SP3_SIGNAL_NMI_SYNC_FLOOD_L
}, {
	.zg_name = "AGPIO86",
	.zg_signal = "BP_LPC_SMI_L",
	.zg_pin = "CW34",
	.zg_id = 86,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LPC_SMI_L, AGPIO86, INVALID, INVALID),
}, {
	.zg_name = "AGPIO87",
	.zg_signal = "BP_SERIRQ",
	.zg_pin = "CW33",
	.zg_id = 87,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(SERIRQ, EMMC_DATA7, AGPIO87, INVALID),
}, {
	.zg_name = "AGPIO88",
	.zg_signal = "BP_LPC_CLKRUN_L",
	.zg_pin = "CW31",
	.zg_id = 88,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LPC_CLKRUN_L, EMMC_DATA5, AGPIO88, INVALID),
}, {
	.zg_name = "AGPIO89",
	.zg_signal = "BP_GENINT1_L",
	.zg_pin = "CY44",
	.zg_id = 89,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(GENINT1_L, PSP_INTR0, AGPIO89, INVALID),
}, {
	/*
	 * The I/O mux for the next four pins technically have entries for the
	 * SD card peripheral. However, while that PCI device exists, it is not
	 * mentioned in the SP3 motherboard guide or FDS, and thus for now we
	 * have opted not to include it here.
	 */
	.zg_name = "EGPIO104",
	.zg_signal = "BP_LAD0",
	.zg_pin = "CV29",
	.zg_id = 104,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LAD0, EMMC_DATA0, INVALID, EGPIO104),
}, {
	.zg_name = "EGPIO105",
	.zg_signal = "BP_LAD1",
	.zg_pin = "CW30",
	.zg_id = 105,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LAD1, EMMC_DATA1, INVALID, EGPIO105),
}, {
	.zg_name = "EGPIO106",
	.zg_signal = "BP_LAD2",
	.zg_pin = "CV32",
	.zg_id = 106,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LAD2, EMMC_DATA2, INVALID, EGPIO106),
}, {
	.zg_name = "EGPIO107",
	.zg_signal = "BP_LAD3",
	.zg_pin = "CS28",
	.zg_id = 107,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LAD3, EMMC_DATA3, INVALID, EGPIO107),
}, {
	.zg_name = "EGPIO108",
	.zg_signal = "BP_ESPI_ALERT_L",
	.zg_pin = "CW24",
	.zg_id = 108,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_UNKNOWN,
	SP3_MUX_ENTRY(LDRQ0_L, ESPI_D1, EGPIO108, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_ESPI_ALERT_L
}, {
	.zg_name = "EGPIO109",
	.zg_signal = "BP_LFRAME_L",
	.zg_pin = "CW27",
	.zg_id = 109,
	.zg_pad = ZEN_GPIO_PAD_TYPE_SD,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(LFRAME_L, EMMC_DS, EGPIO109, INVALID),
}, {
	.zg_name = "EGPIO113",
	.zg_signal = "BP_SCL0",
	.zg_pin = "DA42",
	.zg_id = 113,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(SCL0, I2C2_SCL, EGPIO113, INVALID),
}, {
	.zg_name = "EGPIO114",
	.zg_signal = "BP_SDA0",
	.zg_pin = "DB42",
	.zg_id = 114,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(SDA0, I2C2_SDA, EGPIO114, INVALID),
}, {
	.zg_name = "EGPIO117",
	.zg_signal = "BP_SPI_CLK",
	.zg_pin = "DB30",
	.zg_id = 117,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(ESPI_CLK, EGPIO117, INVALID, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_SPI_CLK
}, {
	.zg_name = "EGPIO118",
	.zg_signal = "BP_SPI_CS1_L",
	.zg_pin = "DB32",
	.zg_id = 118,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(SPI_CS1_L, EGPIO118, INVALID, INVALID),
}, {
	.zg_name = "EGPIO119",
	.zg_signal = "BP_SPI_CS2_L",
	.zg_pin = "DA30",
	.zg_id = 119,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(SPI_CS2_L, ESPI_CS_L, EGPIO119, INVALID),
}, {
	.zg_name = "EGPIO120",
	.zg_signal = "BP_SPI_DI",
	.zg_pin = "DA30",
	.zg_id = 120,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(ESPI_D1, EGPIO120, INVALID, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_SPI_DI
}, {
	.zg_name = "EGPIO121",
	.zg_signal = "BP_SPI_DO",
	.zg_pin = "CY32",
	.zg_id = 121,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(ESPI_D0, EGPIO121, INVALID, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_SPI_DO
}, {
	.zg_name = "EGPIO122",
	.zg_signal = "BP_SPI_WP_L",
	.zg_pin = "DA31",
	.zg_id = 122,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(ESPI_D2, EGPIO122, INVALID, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_SPI_WP_L
}, {
	.zg_name = "AGPIO129",
	.zg_signal = "BP_ESPI_RESET_L",
	.zg_pin = "CY29",
	.zg_id = 129,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(KBRST_L, INVALID, AGPIO129, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_ESPI_RESET_L
}, {
	.zg_name = "EGPIO133",
	.zg_signal = "BP_SPI_HOLD_L",
	.zg_pin = "CY33",
	.zg_id = 133,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_1P8_S0,
	SP3_MUX_ENTRY(ESPI_D3, EGPIO133, INVALID, INVALID),
	.zg_pinovr = ZEN_PIN_OVR_SPI,
	.zg_override = SP3_SIGNAL_SPI_HOLD_L
}, {
	.zg_name = "EGPIO135",
	.zg_signal = "BP_UART0_CTS_L",
	.zg_pin = "CV41",
	.zg_id = 135,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART0_CTS_L, UART2_TXD, EGPIO135, INVALID),
}, {
	.zg_name = "EGPIO136",
	.zg_signal = "BP_UART0_RXD",
	.zg_pin = "CV39",
	.zg_id = 136,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART0_RXD, EGPIO136, INVALID, INVALID),
}, {
	.zg_name = "EGPIO137",
	.zg_signal = "BP_UART0_RTS_L",
	.zg_pin = "CW40",
	.zg_id = 137,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART0_RTS_L, UART2_RXD, EGPIO137, INVALID),
}, {
	.zg_name = "EGPIO138",
	.zg_signal = "BP_UART0_TXD",
	.zg_pin = "CW39",
	.zg_id = 138,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART0_TXD, EGPIO138, INVALID, INVALID),
}, {
	.zg_name = "AGPIO139",
	.zg_signal = "BP_UART0_INTR",
	.zg_pin = "CV38",
	.zg_id = 139,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART0_INTR, AGPIO139, INVALID, INVALID),
}, {
	.zg_name = "EGPIO140",
	.zg_signal = "BP_UART1_CTS_L",
	.zg_pin = "CY38",
	.zg_id = 140,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART1_CTS_L, UART3_TXD, EGPIO140, INVALID),
}, {
	.zg_name = "EGPIO141",
	.zg_signal = "BP_UART1_RXD",
	.zg_pin = "DB36",
	.zg_id = 141,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART1_RXD, EGPIO141, INVALID, INVALID),
}, {
	.zg_name = "EGPIO142",
	.zg_signal = "BP_UART1_RTS_L",
	.zg_pin = "DB38",
	.zg_id = 142,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART1_RTS_L, UART3_RXD, EGPIO142, INVALID),
}, {
	.zg_name = "EGPIO143",
	.zg_signal = "BP_UART1_TXD",
	.zg_pin = "DA37",
	.zg_id = 143,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART1_TXD, EGPIO143, INVALID, INVALID),
}, {
	.zg_name = "AGPIO144",
	.zg_signal = "BP_UART1_INTR",
	.zg_pin = "DA36",
	.zg_id = 144,
	.zg_cap = ZEN_GPIO_C_AGPIO,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(UART1_INTR, AGPIO144, INVALID, INVALID),
}, {
	.zg_name = "EGPIO145",
	.zg_signal = "BP_I2C0_SCL",
	.zg_pin = "DA40",
	.zg_id = 145,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C0_SCL, EGPIO145, INVALID, INVALID),
}, {
	.zg_name = "EGPIO146",
	.zg_signal = "BP_I2C0_SDA",
	.zg_pin = "DB41",
	.zg_id = 146,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C0_SDA, EGPIO146, INVALID, INVALID),
}, {
	.zg_name = "EGPIO147",
	.zg_signal = "BP_I2C1_SCL",
	.zg_pin = "E22",
	.zg_id = 147,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C1_SCL, EGPIO147, INVALID, INVALID),
}, {
	.zg_name = "EGPIO148",
	.zg_signal = "BP_I2C1_SDA",
	.zg_pin = "D22",
	.zg_id = 148,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C1_SDA, EGPIO148, INVALID, INVALID),
}, {
	.zg_name = "EGPIO149",
	.zg_signal = "BP_I2C4_SCL",
	.zg_pin = "CW43",
	.zg_id = 149,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C4_SCL, EGPIO149, INVALID, INVALID),
}, {
	.zg_name = "EGPIO150",
	.zg_signal = "BP_I2C4_SDA",
	.zg_pin = "CV44",
	.zg_id = 150,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C4_SDA, EGPIO150, INVALID, INVALID),
}, {
	.zg_name = "EGPIO151",
	.zg_signal = "BP_I2C5_SCL",
	.zg_pin = "CV42",
	.zg_id = 151,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C5_SCL, EGPIO151, INVALID, INVALID),
}, {
	.zg_name = "EGPIO152",
	.zg_signal = "BP_I2C5_SDA",
	.zg_pin = "CW42",
	.zg_id = 152,
	.zg_pad = ZEN_GPIO_PAD_TYPE_I2C,
	.zg_voltage = ZEN_GPIO_V_1P8_S0 | ZEN_GPIO_V_3P3_S0,
	SP3_MUX_ENTRY(I2C5_SDA, EGPIO152, INVALID, INVALID),
}, {
	.zg_name = "EGPIO9_2",
	.zg_signal = "BP_AGPIO9_2",
	.zg_pin = "D28",
	.zg_id = 256,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO9_2, SGPIO2_DATAOUT, INVALID, INVALID),
}, {
	.zg_name = "EGPIO23_2",
	.zg_signal = "BP_AGPIO23_2",
	.zg_pin = "E28",
	.zg_id = 257,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO23_2, SGPIO2_LOAD, INVALID, INVALID),
}, {
	.zg_name = "EGPIO10_2",
	.zg_signal = "BP_S0A3_GPIO_2",
	.zg_pin = "E26",
	.zg_id = 258,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO10_2, SGPIO2_CLK, INVALID, INVALID),
}, {
	.zg_name = "EGPIO40_2",
	.zg_signal = "BP_AGPIO40_2",
	.zg_pin = "D27",
	.zg_id = 259,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO40_2, SGPIO1_DATAIN, INVALID, INVALID),
}, {
	.zg_name = "EGPIO9_1",
	.zg_signal = "BP_AGPIO9_1",
	.zg_pin = "E25",
	.zg_id = 260,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO9_1, SGPIO1_DATAOUT, INVALID, INVALID),
}, {
	.zg_name = "EGPIO23_1",
	.zg_signal = "BP_AGPIO23_1",
	.zg_pin = "E23",
	.zg_id = 261,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO23_1, SGPIO1_LOAD, INVALID, INVALID),
}, {
	.zg_name = "EGPIO10_1",
	.zg_signal = "BP_S0A3_GPIO_1",
	.zg_pin = "E23",
	.zg_id = 262,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO10_1, SGPIO1_CLK, INVALID, INVALID),
}, {
	.zg_name = "EGPIO40_1",
	.zg_signal = "BP_AGPIO40_1",
	.zg_pin = "D24",
	.zg_id = 263,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(EGPIO40_1, SGPIO1_DATAIN, INVALID, INVALID),
}, {
	.zg_name = "EGPIO16_1",
	.zg_signal = "BP_USB_OC2_L",
	.zg_pin = "C13",
	.zg_id = 264,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(USB_OC2_L, EGPIO16_1, INVALID, INVALID),
}, {
	.zg_name = "EGPIO17_1",
	.zg_signal = "BP_USB_OC3_L",
	.zg_pin = "C14",
	.zg_id = 265,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(USB_OC3_L, EGPIO17_1, INVALID, INVALID),
}, {
	.zg_name = "EGPIO26_1",
	.zg_signal = "BP_PCIE_RST1_L",
	.zg_pin = "A23",
	.zg_id = 266,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PCIE_RST1_L, EGPIO26_1, INVALID, INVALID),
}, {
	.zg_name = "EGPIO26_2",
	.zg_signal = "BP_PCIE_RST2_L",
	.zg_pin = "B28",
	.zg_id = 267,
	.zg_cap = ZEN_GPIO_C_REMOTE,
	.zg_pad = ZEN_GPIO_PAD_TYPE_GPIO,
	.zg_voltage = ZEN_GPIO_V_3P3_S5,
	SP3_MUX_ENTRY(PCIE_RST2_L, EGPIO26_2, INVALID, INVALID),
} };

const size_t zen_gpio_sp3_nents = ARRAY_SIZE(zen_gpio_sp3_data);
