#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Oxide Computer Company
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

# Tests other than interface_version produce results that vary with the
# underlying hardware and ths state/configuration of the service processor;
# they are hence not included in the default runfile.
[/opt/ipcc-tests/tests]
user = root
tests = [
	'interface_version.32',
	'interface_version.64',
	]

